OpenRDV Agent: openrdv::ServerConnection Class Reference
openrdv::ServerConnection Class Reference
Communicate with the server via HTTP/HTTPS.
#include <ServerConnection.h>
Public Member Functions
ServerConnection (const std::string &Host, const std::string &Port)
Create connection with the given host and port.
~ServerConnection ()
Cleanup, close connection.
void sendRegisterDevice (const std::string &UID, const std::string &UIDType)
Send device information to perform registration.
void sendAttestResults (const std::string &UID, const std::string &Token, const AttestResult &Result)
Send results of the most recent test.
boost::property_tree::ptree getResponse ()
Get the response for a just-sent request.
Detailed Description
Communicate with the server via HTTP/HTTPS.
Definition at line 24 of file ServerConnection.h.
Constructor & Destructor Documentation
ServerConnection()
ServerConnection::ServerConnection (const std::string & Host, const std::string & Port) explicit
Create connection with the given host and port.
Parameters
Host Server's domain name or IP address.
Port Server's port.
Definition at line 6 of file ServerConnection.cpp.
Member Function Documentation
getResponse()
boost::property_tree::ptree ServerConnection::getResponse ()
Get the response for a just-sent request.
Returns
http::response<http::dynamic_body> server response.
Definition at line 57 of file ServerConnection.cpp.
References openrdv::LogStreamDecorator< ServerConnection >::info().
sendAttestResults()
void ServerConnection::sendAttestResults (const std::string & UID, const std::string & Token, const AttestResult & Result)
Send results of the most recent test.
Parameters
UID This device's ID.
Token Access token received from server.
Result Attest results.
Definition at line 35 of file ServerConnection.cpp.
References openrdv::LogStreamDecorator< ServerConnection >::info().
sendRegisterDevice()
void ServerConnection::sendRegisterDevice (const std::string & UID, const std::string & UIDType)
Send device information to perform registration.
Parameters
UID Device's unique ID.
UIDType Type of ID, e.g. IMEI.
Definition at line 15 of file ServerConnection.cpp.
References openrdv::LogStreamDecorator< ServerConnection >::info().
The documentation for this class was generated from the following files:
include/ServerConnection.h
src/ServerConnection.cpp